### ISSUE TITLE
Too many arguments, expected arguments "command"

### ISSUE THREAD

**Issue by jover** [digipolisgent/robo-drupal-console#6]
When calling Drupal Console commands using Robo, the following error is thrown:
```
[Symfony\Component\Console\Exception\RuntimeException]  
Too many arguments, expected arguments "command".

...

[DigipolisGent\DrupalConsole\DrupalConsoleStack]  Exit code 1  Time 4.087s
```

Happens for example on the following Drupal Console commands:
```
<?php

class RoboFile extends \Robo\Tasks {

  use DigipolisGent\Robo\Task\DrupalConsole\loadTasks;

  protected function drupal() {
    return $this->taskDrupalConsoleStack('../../vendor/bin/drupal');
  }

  function update() {
    $this->drupal()
      ->uri('mywebsite.example.com')
      ->configImport()
      ->run();
  }
}
```

```
<?php

use \Symfony\Component\Yaml\Yaml;

class RoboFile extends \Robo\Tasks {

  use DigipolisGent\Robo\Task\DrupalConsole\loadTasks;

  protected $config_yaml;

  protected function drupal() {
    return $this->taskDrupalConsoleStack('../../vendor/bin/drupal');
  }

  function installSite() {
    $this->drupal()
      ->uri($this->config('site_uri'))
      ->siteName('My Website')
      ->siteMail('no-reply@mywebsite.example.com')
      ->langcode('en')
      ->accountName('admin')
      ->accountPass('admin123')
      ->accountMail('no-reply@mywebsite.example.com')
      ->dbType('mysql')
      ->dbHost($this->config('db_host'))
      ->dbName($this->config('db_name'))
      ->dbUser($this->config('db_user'))
      ->dbPass($this->config('db_pass'))
      ->dbPrefix($this->config('db_prefix'))
      ->siteInstall('my_website_profile')
      ->run();
  }

  protected function config($key, $default = null) {
    $config = $this->getConfig();
    if (array_key_exists($key, $config)) {
      return $config[$key];
    }
    return $default;
  }

  protected function getConfig() {
    if (empty($this->config_yaml)) {
      $this->config_yaml = Yaml::parse(__DIR__ . '/config.yml');
    }
    return $this->config_yaml;
  }
}
```

**Comment by jover** [comment]
This problem can be solved by changing:
`$this->arguments .= null == $value ? '' : ' ' . static::escape($value);`
... into:
`$this->arguments .= null == $value ? '' : '="' . static::escape($value) . '"';`

But this is Robo-code... see below:
```
trait CommandArguments
{

  ...

    public function option($option, $value = null)
    {
        if ($option !== null and strpos($option, '-') !== 0) {
            $option = "--$option";
        }
        $this->arguments .= null == $option ? '' : ' ' . $option;
        $this->arguments .= null == $value ? '' : ' ' . static::escape($value);
        return $this;
  }
  
  ...
  
}
```

Should the Robo Drupal Console integration do a workaround for this?

**Comment by daften** [comment]
Thanks for reporting this! I've talked this over with @Jelle-S  We can work around this, and will probably have to, because ATM we think this is because commands defined with symfony console, only accept options with `--option=value` instead of `--option value`.
We think we can whip up a workaround sometime next week, so stay tuned. We'll try to get this propagated to robo itself as well (and symfony).

**Comment by dustinleblanc** [comment]
I just ran into this too. It just occurred to me this morning that Drupal Console is running Symfony Commands, so http://robo.li/tasks/Base/#symfonycommand might be useful too?

**Comment by Jelle-S** [comment]
I created #7 to have a quickfix for this issue.

@dustinleblanc your suggestion looks interesting. But it would mean quite a big rewrite. I might revisit that is the future. Thanks for your suggestion!

**Comment by daften** [comment]
@dustinleblanc I've created a follow-up issue for your fix, which should be inherently better, but too much of a refactor for us to do right now (we're creating our entire D8 workflow atm, that's work enough). See #7  and thanks for alerting us to that possibility!
A PR is always welcome though :)
